CREATE TABLE C_ADDRESS(
ID int primary key not null,
CUSTOMER_ID int,
COUNTRY_ID tinyint,
CITY_ID int,
TOWN_ID int,
DISTRICT_ID int,
ADDRESS_TEXT varchar(250),
	CONSTRAINT C_ADDRESS_CUSTOMERS_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID),
	CONSTRAINT C_ADDRESS_COUNTRIES_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (ID),
	CONSTRAINT C_ADDRESS_CITIES_FK FOREIGN KEY (CITY_ID) REFERENCES CITIES (ID),
	CONSTRAINT C_ADDRESS_TOWNS_FK FOREIGN KEY (TOWN_ID) REFERENCES TOWNS (ID),
	CONSTRAINT C_ADDRESS_DISTRICTS_FK FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICTS (ID)
);