CREATE TABLE ORDER_DETAILS(
ID int primary key not null,
ORDER_ID int,
PRODUCT_ID int,
AMOUNT int,
UNIT_PRICE int,
TOTAL int,
	CONSTRAINT ORDER_DETAILS_ORDERS_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
	CONSTRAINT ORDER_DETAILS_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);